server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    datacenter: default
    environment: local
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 5000
    renewalPercentThreshold: 0.33

  instance:
    hostname: localhost
